// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqJa4ZJJG4LJ-P7Sx1n7uDgFcvX1ACw5c',
    appId: '1:52896062000:web:c75a87c0394ca2d1b2abf5',
    messagingSenderId: '52896062000',
    projectId: 'voter-apps',
    authDomain: 'voter-apps.firebaseapp.com',
    storageBucket: 'voter-apps.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpelj5cyM5ywpp4vDCvtqXbNlKASrkC-g',
    appId: '1:52896062000:android:33f58adb294e8b63b2abf5',
    messagingSenderId: '52896062000',
    projectId: 'voter-apps',
    storageBucket: 'voter-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5O5br_AnUwlkxUxi0XpCMArrF6GYoKzw',
    appId: '1:52896062000:ios:d3f966c98506e547b2abf5',
    messagingSenderId: '52896062000',
    projectId: 'voter-apps',
    storageBucket: 'voter-apps.firebasestorage.app',
    iosBundleId: 'com.example.votersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5O5br_AnUwlkxUxi0XpCMArrF6GYoKzw',
    appId: '1:52896062000:ios:d3f966c98506e547b2abf5',
    messagingSenderId: '52896062000',
    projectId: 'voter-apps',
    storageBucket: 'voter-apps.firebasestorage.app',
    iosBundleId: 'com.example.votersApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqJa4ZJJG4LJ-P7Sx1n7uDgFcvX1ACw5c',
    appId: '1:52896062000:web:15eff87a4eaccf16b2abf5',
    messagingSenderId: '52896062000',
    projectId: 'voter-apps',
    authDomain: 'voter-apps.firebaseapp.com',
    storageBucket: 'voter-apps.firebasestorage.app',
  );
}
